CREATE TABLE IF NOT EXISTS lists (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  slug CHAR(20) NOT NULL UNIQUE,
  title VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS todos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  list_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  status ENUM('todo','doing','done') NOT NULL DEFAULT 'todo',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_list (list_id, id),
  FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4;
